name: Build Controls.Sample.Gtk
on: [push, pull_request]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-20.04
    env:
      GtkSharpVersion: 3.24.24.77-develop
    steps:
      - name: Checkout MAUI repo
        uses: actions/checkout@v2
        with:
          path: maui
      # We also tested using 6.0.111 for both projects
      # but MAUI failed to build on this version with this error:
      # Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
      # so instead we added support for 6.0.4xx to GtkSharp
      - name: Setup .NET SDK 6.0.300
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.300'
      - name: Install gtk workload
        run: |
            dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.PERSONAL_ACCESS_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GtkSharp/index.json"
            # For some reason automatic workload manifest detection doesn't work (see https://github.com/GtkSharp/GtkSharp/issues/355#issuecomment-1446262239), so download and uzip mainfest file manually
            wget --user ${{ github.actor }} --password ${{ secrets.PERSONAL_ACCESS_TOKEN }} https://nuget.pkg.github.com/GtkSharp/download/gtksharp.net.sdk.gtk.manifest-6.0.300/$GtkSharpVersion/gtksharp.net.sdk.gtk.manifest-6.0.300.nupkg
            DOTNET_DIR=/home/runner/.dotnet
            WORKLOAD_MANIFEST_DIR=$DOTNET_DIR/sdk-manifests/6.0.300/gtksharp.net.sdk.gtk
            unzip -j gtksharp.net.sdk.gtk.manifest-6.0.300.nupkg "data/*" -d $WORKLOAD_MANIFEST_DIR/
            rm gtksharp.net.sdk.gtk.manifest-6.0.300.nupkg
            chmod 764 $WORKLOAD_MANIFEST_DIR/*
            dotnet workload search
            dotnet workload install gtk
      - name: Build MAUI
        run: |
            cd maui
            dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.PERSONAL_ACCESS_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GtkSharp/index.json"
            dotnet build Microsoft.Maui.BuildTasks.slnf
            dotnet build ./src/Controls/samples/Controls.Sample.Gtk/Controls.Sample.Gtk.csproj
            cd ..
